// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8-ICtv56vxy8uGOQ5XmBbBBGblK0Jc74',
    appId: '1:77605210564:android:2a79caf72362850b7bbc91',
    messagingSenderId: '77605210564',
    projectId: 'accesscampus-93efc',
    storageBucket: 'accesscampus-93efc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAalCPemFY9xgHLIpNGObm7bgjtoFFP13w',
    appId: '1:77605210564:ios:f4df164328b5504d7bbc91',
    messagingSenderId: '77605210564',
    projectId: 'accesscampus-93efc',
    storageBucket: 'accesscampus-93efc.appspot.com',
    iosBundleId: 'com.example.qrTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAalCPemFY9xgHLIpNGObm7bgjtoFFP13w',
    appId: '1:77605210564:ios:b3ad4f1c6c6a83cc7bbc91',
    messagingSenderId: '77605210564',
    projectId: 'accesscampus-93efc',
    storageBucket: 'accesscampus-93efc.appspot.com',
    iosBundleId: 'con.test.a',
  );
}
